name: servercam
version: '${project.version}'
main: com.parknich.servercam.ServerCam
softdepend: [Citizens, Sentinel]
commands:
  c:
    description: Enter freecam
    usage: /c
  s:
    description: Exit freecam
    usage: /s
